# Auto-generated mapping from 3-Style Corner-UFR.xlsx.
# Do not edit manually.

CORNER_THREE_STYLE = {
    'AB': "R D' R2 D R U2 R' D' R U2 R D R'",
    'AC': "R' U' D' R2 U' R' D R U R' D' R' U D R",
    'AD': "R' D R U' R D' R' U2 R D R' U R' D' R U2",
    'AE': "R' D R U2 R' D' R U' R' D R U' R' D' R",
    'AF': "U' R U2 D R D' R' U2 R D R' D' R' U",
    'AG': "U' R D' R' U2 R D R' U'",
    'AH': "R' D R U2 R' D' R U2",
    'AI': "R' F' R U D R' D' R U R' D R U2 D' R' F R",
    'AK': "D R' D' R U2 R' D R U2 D'",
    'AL': "D' R' D R U2 R' D' R U2 D",
    'AM': "R' D' R U2 R' D R U2",
    'AN': "U R D R D' R' U2 R D R' U2 D' R' U'",
    'AO': "R' D R U2 R' D' R U R' D R U R' D' R",
    'AP': "U' R D R' U2 R D' R' U'",
    'AR': "R' U2 D' R' D R U2 R' D' R D R",
    'AS': "U' D' R D R' U2 R D' R' U' D",
    'AT': "U' D R D' R' U2 R D R' U' D'",
    'AW': "R F' R' U' R D R' U2 R D' R' U' R F R'",
    'BA': "R D' R' U2 R' D R U2 R' D' R2 D R'",
    'BC': "R B D R' U R D' R' U' R B' R'",
    'BD': "F' R U R' D' R U2 R' D R U R' F",
    'BE': "R D' R' U R' D R U' R' D' R U' R D R' U",
    'BF': "U2 R U D R' U' R D' R' U R U' R' U2",
    'BG': "R D' R' U R' D R U' R' D' R2 D R'",
    'BH': "F' D' R U' R' D R U R' F",
    'BI': "D R U2 R D' R' U2 R D R2 D'",
    'BK': "D R U' R D' R' U R D R2 D'",
    'BL': "U R D' R' D R U' R' D' R U D R' U'",
    'BM': "D R2 U' R' U' R D' R' U R U D R2 D'",
    'BN': "R B R' U' R D R' U2 R D' R' U' R B' R'",
    'BO': "R D' R' U' R' D R U R' D' R2 D R'",
    'BR': "D R U' D' R' U R D R' U' R U R' D'",
    'BS': "R U R2 D' R2 U' R2 U R2 D R2 U' R",
    'BW': "D R U' R' U' R D' R' U2 R D R' U' R U R' D'",
    'BY': "F' R U2 R' D' R U R' D R U R' F",
    'BZ': "D R U R D' R' U' R D R2 D'",
    'CA': "R' U' D' R D R U' R' D' R U R2 U D R",
    'CB': "R B R' U R D R' U' R D' B' R'",
    'CD': "R U' R' U' R D' R' U2 R D R' U' R U R'",
    'CE': "R' B R U R' D' R U' R' D B' R",
    'CF': "F R2 D' R' U' R D R' U R' F'",
    'CH': "R B R' U2 D R' D' R U' R' D R U' D' R B' R'",
    'CI': "R U2 R D' R' U2 R D R2",
    'CK': "F R U2 R D' R' U R D R' U R' F'",
    'CL': "R2 U' R' U R D' R' U' R U D R2",
    'CM': "R U' R D' R' U R D R2",
    'CN': "D' R D R' U R' F R2 D' R' D R' F' R U'",
    'CO': "R' B R U' R' D' R U R' D B' R",
    'CP': "U' R' D' R D R' U' R D' R' U D R U",
    'CR': "R U' D' R' U R D R' U' R U R'",
    'CT': "R2 U' R' U' R D' R' U R U D R2",
    'CW': "R B R' U2 R' D R U' R' D' R U' R B' R'",
    'CY': "R B R' U R D' R' U' R D B' R'",
    'CZ': "R U R D' R' U' R D R2",
    'DA': "U2 R' D R U' R D' R' U2 R D R' U R' D' R",
    'DB': "F' R U' R' D' R U2 R' D R U' R' F",
    'DC': "R U' R' U R D' R' U2 R D R' U R U R'",
    'DE': "U R' D R U' R D' R' U' R D R' U R' D' R",
    'DF': "R U' R' U2 R' D' R U2 R' D R2 U R'",
    'DG': "R U' R' U D' R D R' U2 R D' R' U D R U R'",
    'DH': "U' R' D R U' R D' R' U R D R2 D' R U",
    'DI': "R U' R' U2 D' R' D R U2 R' D' R D R U R'",
    'DK': "R U' R' U2 R' D R U2 R' D' R2 U R'",
    'DN': "U' D' R' U2 R' D R U2 R' D' R2 U D",
    'DO': "U' R' D R U' R D' R' U R D R' U R' D' R",
    'DP': "D' R U' R2 D R2 U R' U' R2 D' R2 U D",
    'DR': "U R' U' D' R U R' D R U' R' U R U'",
    'DS': "U' D' R' U R' D R U' R' D' R2 U D",
    'DT': "R U' R' U R D R' U2 R D' R' U R U R'",
    'DW': "R U' R' U2 D R' D' R U2 R' D R D' R U R'",
    'DY': "U' D' R' U' R' D R U R' D' R2 U D",
    'DZ': "D' R U2 D R' D' R U' R' D R U' D' R' D",
    'EA': "R' D R U R' D' R U R' D R U2 R' D' R",
    'EB': "U' R D' R' U R' D R U R' D' R U' R D R'",
    'EC': "R' B D' R U R' D R U' R' B' R",
    'ED': "R' D R U' R D' R' U R D R' U R' D' R U'",
    'EF': "R2 D' R U' R' D R U R",
    'EG': "U' R D' R' U R D R'",
    'EH': "R' D R U R' D' R U'",
    'EI': "R U2 R D R' U2 R D' R2",
    'EK': "D R' D' R U R' D R U' D'",
    'EL': "D' R' D R U R' D' R U' D",
    'EM': "R' D' R U R' D R U'",
    'EO': "R U R' U R' D' R U R' D R U2 R U' R'",
    'EP': "U' R D R' U R D' R'",
    'ES': "U' D' R D R' U R D' R' D",
    'ET': "U' D R D' R' U R D R' D'",
    'EW': "R F' R' U' R D R' U R D' F R'",
    'EY': "R2 D' R U2 R' D R U2 R",
    'EZ': "R U R D R' U' R D' R2",
    'FA': "R' U' D R U R' D' R U2 R' D R U R' U D' R",
    'FB': "R B R' U R D R' U R D' R' U2 R B' R'",
    'FC': "R2 D' R2 U' R U R2 D R2 U' R' U",
    'FD': "R U' R2 D' R U2 R' D R U2 R U R'",
    'FE': "R' U' R' D' R U R' D R2",
    'FG': "U' R U' D' R' U R D R' U' R U R' U",
    'FH': "R' U' D R U R' D' R U' R' U R",
    'FK': "D R' U' D' R U R' D R U' R' U R D'",
    'FL': "D' R' U' D R U R' D' R U' R' U R D",
    'FM': "R' U' D' R U R' D R U' R' U R",
    'FN': "U' R' U2 D' R' D R U2 R' D' R D R U",
    'FP': "R' U' R' D' R U2 R' D R U' R",
    'FR': "R' F R U R' D R U' R' D' F' R",
    'FS': "U2 R U R' U' R D' R' U R U' D R' U2",
    'FT': "F D' R U R' D R U' R' F'",
    'FW': "U' R' U R U' R' D R U R' U' D' R U",
    'FY': "R' U' R' D' R U' R' D R U2 R",
    'FZ': "R U' R' U' R' D' R U' R' D R U2 R U R'",
    'GA': "U R D' R' U2 R D R' U",
    'GB': "R D' R2 D R U R' D' R U' R D R'",
    'GD': "R U' R' U' D' R D R' U2 R D' R' U' D R U R'",
    'GE': "R D' R' U' R D R' U",
    'GF': "R' U' R2 D' R' U' R D R' U R' U R",
    'GH': "R' D F' D' R D R' F R D'",
    'GI': "R U2 D' R D R' U2 R D' R' D R'",
    'GK': "R' F' R U' R D' R' U R D R2 F R",
    'GL': "U R U' R D' R' U' R D R' U2 R' U'",
    'GM': "R U' D' R D R' U R D' R' D R'",
    'GN': "U R2 D' R' U2 R D R' U2 R' U'",
    'GO': "U2 R D' R' U R D R' U",
    'GP': "R' U R2 D' R' U' R D R' U R' U' R",
    'GR': "D' R U' D R' U R D' R' U' R U R' D",
    'GT': "U D' R' U2 R D R' U2 R U'",
    'GW': "F' R U' D' R D R' U R' F R2 D' R' D R'",
    'GY': "R D' R U R' U' R D R' U R U' D' R' D R'",
    'GZ': "R U D' R D R' U' R D' R' D R'",
    'HA': "U2 R' D R U2 R' D' R",
    'HB': "F' R U' R' D' R U R' D F",
    'HC': "R B R' U D R' D' R U R' D R U2 D' R B' R'",
    'HD': "U' R' D R2 D' R' U' R D R' U R' D' R U",
    'HE': "U R' D R U' R' D' R",
    'HF': "R' U' R U R' D R U' R' U D' R",
    'HG': "D R' F' R D' R' D F D' R",
    'HI': "D R' F2 R D' R' D F2 D' R",
    'HL': "U D R U' R' D' R U R' U'",
    'HM': "R' D' R D R' F R U' D' R' D R U R' F' R",
    'HN': "U R U R' D R U2 R' D' R U R' U'",
    'HO': "U' R' D R U R' D' R",
    'HP': "R' U R U R' D R U' R' U' D' R",
    'HR': "R' U R U' R' D R U R' U' D' R",
    'HS': "R B R' U R' D R U' D' R B' R' D R' D' R",
    'HT': "R' U' R U2 R' D R U2 R' U D' R",
    'HY': "R B' R2 D R D' R B R' D R' D' R",
    'HZ': "U R2 D R U' R' D' R U R U'",
    'IA': "R' F R U D R' D' R U R' D R U2 D' R' F' R",
    'IB': "D R2 D' R' U2 R D R' U2 R' D'",
    'IC': "R2 D' R' U2 R D R' U2 R'",
    'ID': "R U' R' D' R' D R U2 R' D' R U2 D R U R'",
    'IE': "R2 D R' U2 R D' R' U2 R'",
    'IG': "R D' R D R' U2 R D' R' U2 D R'",
    'IH': "R' D F2 D' R D R' F2 R D'",
    'IK': "R U R' D R U2 R' D' R U R'",
    'IL': "D' R' D F2 D' R D R' F2 R",
    'IM': "D R U R' D' R U2 R' D R U R' D'",
    'IN': "R' U' R2 D' R2 D R2 U R2 D' R2 D R'",
    'IP': "R U D' R' D R U2 R' D' R U D R'",
    'IR': "R D R D' R' U2 R D R' U2 D' R'",
    'IS': "U' D' R D R' U R' F R2 D' R' D R' F' R",
    'IT': "R U R' D' R U2 R' D R U R'",
    'IW': "R U D R' D' R U2 R' D R U D' R'",
    'IY': "R U R' U2 D' R' D R U2 R' D' R D R U' R'",
    'IZ': "R U' R' U' D' R' D R U' R' D' R U2 D R U R'",
    'KA': "U2 D R' D' R U2 R' D R D'",
    'KB': "D R2 D' R' U' R D R' U R' D'",
    'KC': "F R U' R D' R' U' R D R' U2 R' F'",
    'KD': "R U' R2 D R U2 R' D' R U2 R U R'",
    'KE': "U D R' D' R U' R' D R D'",
    'KF': "D R' U' R U R' D' R U' R' U D R D'",
    'KG': "R' F' R2 D' R' U' R D R' U R' F R",
    'KI': "R U' R' D R U2 R' D' R U' R'",
    'KL': "D' R' D F' D' R D R' F R",
    'KM': "D R U R' D' R U' R'",
    'KN': "U' R B' R' D R' D' R2 B R' U R' D R D'",
    'KO': "U' D R' D' R U R' D R D'",
    'KP': "R' F' R2 D R' U' R D' R' U R' F R",
    'KR': "D R' U R U' R' D' R U R' U' D R D'",
    'KS': "R' F' R D' R D R' U' R D' R' U D R' F R",
    'KT': "D R D' R D R' U' R D' R' U D R' D'",
    'KY': "R B' R' D R' D' R2 B R2 D R D'",
    'KZ': "R U2 R' D R U' R' D' R U' R'",
    'LA': "U2 D' R' D R U2 R' D' R D",
    'LB': "U R U' D' R' D R U R' D' R D R' U'",
    'LC': "R2 U' D' R' U R D R' U' R U R2",
    'LE': "U D' R' D R U' R' D' R D",
    'LF': "D' R' U' R U R' D R U' R' U D' R D",
    'LG': "U R U2 R D' R' U R D R' U R' U'",
    'LH': "U R U' R' D R U R' U' D'",
    'LI': "R' F2 R D' R' D F2 D' R D",
    'LK': "R' F' R D' R' D F D' R D",
    'LN': "U' R' U R D R' U2 R D' R' U R U",
    'LO': "U' D' R' D R U R' D' R D",
    'LP': "U R U' R' D' R U R' U' D",
    'LR': "D' R' U R U' R' D R U R' U' D' R D",
    'LS': "D' R' U R U R' D R U' R' U' D' R D",
    'LT': "D R' U R U' R D' R' U R D R2 U' R D'",
    'LW': "U' R2 D R2 U R U' R2 D' R2 U R'",
    'LY': "U' R' U2 R D R' U R D' R' U R U",
    'LZ': "R U R' U' R' D' R U R' D R2 U' R'",
    'MA': "U2 R' D' R U2 R' D R",
    'MB': "D R2 U' D' R' U' R D R' U R U R2 D'",
    'MC': "R2 D' R' U' R D R' U R'",
    'ME': "U R' D' R U' R' D R",
    'MF': "R' U' R U R' D' R U' R' U D R",
    'MG': "R D' R D R' U' R D' R' U D R'",
    'MH': "U' R U' R' U R' D R U' R' D' R2 U R' U",
    'MI': "D R U' R' D' R U2 R' D R U' R' D'",
    'MK': "R U R' D R U' R' D'",
    'MN': "R' F' R U' R' D' R U2 R' D R U' R' F R",
    'MO': "U' R' D' R U R' D R",
    'MP': "R' U R U R' D' R U' R' U' D R",
    'MR': "R' U R U' R' D' R U R' U' D R",
    'MS': "D' R' F' R2 D R' U' R D' R' U R' F R D",
    'MT': "R U R' D' R U' R' D",
    'MW': "R U D R' D' R U' R' D R D' R'",
    'MY': "R B' R2 D' R U R' D R U' R B R'",
    'MZ': "D R U2 R' D' R U' R' D R U' R' D'",
    'NA': "U R U2 D R D' R' U2 R D R' D' R' U'",
    'NB': "R B R' U R D R' U2 R D' R' U R B' R'",
    'NC': "U R' F R D' R D R2 F' R U' R D' R' D",
    'ND': "R B R' U2 D' R' D R U2 R' D' R D R B' R'",
    'NF': "U' R' D' R' D R U2 R' D' R U2 D R U",
    'NG': "U R U2 R D' R' U2 R D R2 U'",
    'NH': "U R U' R' D R U2 R' D' R U' R' U'",
    'NI': "R' F' R U D R' D' R U2 R' D R U D' R' F R",
    'NK': "D R' D' R U' R B' R2 D R D' R B R' U",
    'NL': "U' R' U' R D R' U2 R D' R' U' R U",
    'NM': "R' F' R U R' D' R U2 R' D R U R' F R",
    'NO': "U' R2 D' R U2 R' D R U2 R U",
    'NP': "U R U' R' D' R U2 R' D R U' R' U'",
    'NS': "U' R' U' R D' R' U2 R D R' U' R U",
    'NT': "U D R U2 R D' R' U2 R D R2 U' D'",
    'NW': "U' R2 D R U2 R' D' R U2 R U",
    'NY': "U R U2 R D R' U2 R D' R2 U'",
    'NZ': "R U R2 D R2 D' R2 U' R2 D R2 D' R",
    'OA': "R' D R U' R' D' R U' R' D R U2 R' D' R",
    'OB': "R D' R2 D R U' R' D' R U R D R'",
    'OC': "R' B D' R U' R' D R U R' B' R",
    'OD': "R' D R U' R D' R' U' R D R' U R' D' R U",
    'OE': "R F R' U R' D' R U' R' D R2 F' R'",
    'OG': "U' R D' R' U' R D R' U2",
    'OH': "R' D R U' R' D' R U",
    'OK': "D R' D' R U' R' D R U D'",
    'OL': "D' R' D R U' R' D' R U D",
    'OM': "R' D' R U' R' D R U",
    'ON': "U' R' U2 R' D' R U2 R' D R2 U",
    'OP': "U' R D R' U' R D' R' U2",
    'OR': "R' U' D' R' D R U R' D' R D R",
    'OS': "U' D' R D R' U' R D' R' U2 D",
    'OT': "U' D R D' R' U' R D R' U2 D'",
    'OW': "U' R F' D R' U' R D' R' U R F R' U",
    'OY': "U' R' U' R' D' R U R' D R2 U",
    'OZ': "R U R' U2 R' D' R U2 R' D R2 U' R'",
    'PA': "U R D R' U2 R D' R' U",
    'PC': "U' R' U' D' R D R' U R D' R' D R U",
    'PD': "R U' D' R2 D R U2 R' D' R U2 R U D R'",
    'PE': "R D R' U' R D' R' U",
    'PF': "R' U R' D' R U2 R' D R U R",
    'PG': "R' U R U' R D' R' U R D R2 U' R",
    'PH': "R' U D R U R' D' R U' R' U' R",
    'PI': "R U' D' R' D R U2 R' D' R U' D R'",
    'PK': "R' F' R U' R D R' U R D' R2 F R",
    'PL': "U D' R U' R' D R U R' U'",
    'PM': "R' U D' R U R' D R U' R' U' R",
    'PN': "U R U R' D' R U2 R' D R U R' U'",
    'PO': "U2 R D R' U R D' R' U",
    'PR': "U' R U R' U' R D R' U R U' D' R' U",
    'PS': "U' R' U' R D' R' U R U D",
    'PW': "U' R2 D R U R' D' R U' R U",
    'PY': "R' U R' D' R U R' D R U2 R",
    'PZ': "R U R' U' R D R' U R U' R' U' R D' R' U",
    'RA': "R' D' R' D R U2 R' D' R U2 D R",
    'RB': "D R U' R' U R D' R' U' R U D R' D'",
    'RC': "R U' R' U R D' R' U' R U D R'",
    'RD': "U R' U' R U R' D' R U' R' U D R U'",
    'RF': "R' F D R U R' D' R U' R' F' R",
    'RG': "D' R U' R' U R D R' U' R U D' R' D",
    'RH': "R' U D R U' R' D' R U R' U' R",
    'RI': "R U2 D R D' R' U2 R D R' D' R'",
    'RK': "D R' U D' R U' R' D R U R' U' R D'",
    'RL': "D' R' U D R U' R' D' R U R' U' R D",
    'RM': "R' U D' R U' R' D R U R' U' R",
    'RO': "R' D' R' D R U' R' D' R U D R",
    'RP': "U' R U D R' U' R D' R' U R U' R' U",
    'RS': "U' D' R U D R' U' R D' R' U R U' R' U D",
    'RT': "R U' R' U R D R' U' R U D' R'",
    'RW': "U' R2 D R2 U R' U' R2 D' R2 U R",
    'RY': "R B' R' U' R D' R' U R D B R'",
    'RZ': "U R2 D' R U' R' D R U R U'",
    'SA': "U D' R D R' U2 R D' R' U D",
    'SB': "R' U R2 D' R2 U' R2 U R2 D R2 U' R'",
    'SD': "U' D' R2 D R U R' D' R U' R U D",
    'SE': "D' R D R' U' R D' R' U D",
    'SF': "U2 R U D' R' U' R D R' U R U' R' U2",
    'SH': "R' D R D' R B R' U D R' D' R U' R B' R'",
    'SI': "R' F R D' R D R2 F' R U' R D' R' U D",
    'SK': "R' F' R U' D' R D R' U R D' R' D R' F R",
    'SL': "D' R' U D R U R' D' R U' R' U' R D",
    'SM': "D' R' F' R U' R D R' U R D' R2 F R D",
    'SN': "U' R' U R D' R' U2 R D R' U R U",
    'SO': "U2 D' R D R' U R D' R' U D",
    'SP': "U' D' R' U' R D R' U R U",
    'SR': "U R2 D' R2 U' R U R2 D R2 U' R'",
    'ST': "U' D R D' B D R' D' R B' R' U",
    'SW': "U' R2 D F' D' R D R' F R D' R U",
    'SY': "U' R' U2 R D' R' U R D R' U R U",
    'SZ': "U' R' F R D' R D R2 F' R2 D' R' U D",
    'TA': "U D R D' R' U2 R D R' U D'",
    'TC': "R2 U' D' R' U' R D R' U R U R2",
    'TD': "D' R U D R' D' R U' R' D R D' R' D",
    'TE': "D R D' R' U' R D R' U D'",
    'TF': "F R U R' D' R U' R' D F'",
    'TG': "U R' U2 R D' R' U2 R U' D",
    'TH': "R' U' D R U2 R' D' R U2 R' U R",
    'TI': "R U' R' D' R U2 R' D R U' R'",
    'TK': "D R U' D' R D R' U R D' R' D R' D'",
    'TL': "D R' U R2 D' R' U' R D R' U R' U' R D'",
    'TM': "D' R U R' D R U' R'",
    'TN': "U D R2 D' R' U2 R D R' U2 R' U' D'",
    'TO': "U2 D R D' R' U R D R' U D'",
    'TR': "R U' D R' U R D' R' U' R U R'",
    'TS': "D' R D R' U R' D' R U' R' D R2 D' R' D",
    'TW': "U' R2 U D R U' R' D' R U R' U' R2 U",
    'TY': "D' R U R' U' R' D R U R' D' R D R U' R'",
    'TZ': "R U2 R' D' R U' R' D R U' R'",
    'WA': "R F' R' U R D R' U2 R D' R' U R F R'",
    'WB': "D R U' R' U R D' R' U2 R D R' U R U R' D'",
    'WC': "R B R' U R' D R U R' D' R U2 R B' R'",
    'WD': "R U' R' D R' D' R U2 R' D R U2 D' R U R'",
    'WE': "R F' D R' U' R D' R' U R F R'",
    'WF': "U' R' U D R U' R' D' R U R' U' R U",
    'WG': "R D' R D R2 F' R U' R D' R' U D R' F",
    'WI': "R U' D R' D' R U2 R' D R U' D' R'",
    'WL': "R U' R2 D R2 U R' U' R2 D' R2 U",
    'WM': "R D R' D' R U R' D R U' D' R'",
    'WN': "U' R' U2 R' D R U2 R' D' R2 U",
    'WO': "U' R F' R' U' R D R' U R D' F R' U",
    'WP': "U' R' U R' D R U' R' D' R2 U",
    'WR': "R' U' R2 D R2 U R U' R2 D' R2 U",
    'WS': "U' R' D R' F' R D' R' D F D' R2 U",
    'WT': "R D R2 U R U' R2 D' R2 U R' U' R",
    'WY': "U' R' U' R' D R U R' D' R2 U",
    'WZ': "R U2 D R' D' R U' R' D R U' D' R'",
    'YB': "U R' F R2 D R' U' R D' R' U R' F' R U'",
    'YC': "R B D' R' U R D R' U' R B' R'",
    'YD': "U' D' R2 D R U' R' D' R U R U D",
    'YE': "R' U2 R' D' R U2 R' D R2",
    'YF': "R' U2 R' D' R U R' D R U R",
    'YG': "R D' R U D R' U' R D' R' U R U' R' D R'",
    'YH': "R' D R D' R B' R' D R' D' R2 B R'",
    'YI': "R U R' D' R' D R U2 R' D' R U2 D R U' R'",
    'YK': "D R' D' R2 B' R2 D R D' R B R'",
    'YL': "U' R' U' R D R' U' R D' R' U2 R U",
    'YM': "R B' R' U R' D' R U' R' D R2 B R'",
    'YN': "U R2 D R' U2 R D' R' U2 R' U'",
    'YO': "U' R2 D' R U' R' D R U R U",
    'YP': "R' U2 R' D' R U' R' D R U' R",
    'YR': "R B' D' R' U' R D R' U R B R'",
    'YS': "U' R' U' R D' R' U' R D R' U2 R U",
    'YT': "R U R' D' R' D R U' R' D' R U R U' R' D",
    'YW': "U' R2 D R U' R' D' R U R U",
    'ZB': "D R2 D' R' U R D R' U' R' D'",
    'ZC': "R2 D' R' U R D R' U' R'",
    'ZD': "D' R U D R' D' R U R' D R U2 D' R' D",
    'ZE': "R2 D R' U R D' R' U' R'",
    'ZF': "R U' R' U2 R' D' R U R' D R U R U R'",
    'ZG': "R D' R D R' U R D' R' U' D R'",
    'ZH': "U R' U' R' D R U R' D' R2 U'",
    'ZI': "R U' R' U2 D' R' D R U R' D' R U D R U R'",
    'ZK': "R U R' D R U R' D' R U2 R'",
    'ZL': "R U R2 D' R U' R' D R U R U' R'",
    'ZM': "D R U R' D' R U R' D R U2 R' D'",
    'ZN': "R' D R2 D' R2 U R2 D R2 D' R2 U' R'",
    'ZO': "R U R2 D' R U2 R' D R U2 R U' R'",
    'ZP': "U' R D R' U R U R' U' R D' R' U R U' R'",
    'ZR': "U R' U' R' D' R U R' D R2 U'",
    'ZS': "U' D' R D R2 F R2 D' R' D R' F' R U",
    'ZT': "R U R' D' R U R' D R U2 R'",
    'ZW': "R U D R' D' R U R' D R U2 D' R'",
}

# Auto-generated mapping from 3-Style Edge-UR.xlsx.
# Do not edit manually.

EDGE_THREE_STYLE = {
    'AB': "S' R B' R S R2 S' R B R' S",
    'AC': "S R B' E' R2 E R2 B R' S'",
    'AD': "R F R2 E R U R' E' R U' R F' R'",
    'AE': "R U' R S2 R' U R S2 R2",
    'AF': "R E' R' U R E R' U'",
    'AG': "R' E R U R' E' R U'",
    'AH': "U2 R S R' U R S' R' U",
    'AI': "U' S R B' R' S' R B R' U",
    'AJ': "R E2 R' U R E2 R' U'",
    'AK': "R U' R' U2 R' U' R U' R U R2 U R U'",
    'AL': "M' U M U M' U M U",
    'AM': "U2 R' S' R U R' S R U",
    'AN': "U2 R S' R' U R S R' U",
    'AO': "R U2 R2 U' R U R U2 R' U' R' U R",
    'AP': "R' E' R U R' E R U'",
    'AR': "R' E2 R U R' E2 R U'",
    'AS': "U2 R S2 R' U R S2 R' U",
    'AT': "R' U R U' M U R' U' r",
    'AW': "R E' R2 E R U R' E' R2 E R' U'",
    'AZ': "S U R' E' R U' R' E R S'",
    'BA': "S' R B' R' S R2 S' R' B R' S",
    'BC': "S' R B R' S R2 S' R' B' R' S",
    'BD': "S' R' F' R S R2 S' R F R S",
    'BE': "S' U2 R2 S R2 U2",
    'BF': "R2 S' R' E' R2 E R' S R2",
    'BG': "R2 S' R E R2 E' R S R2",
    'BI': "R F R S' R2 S R F' R'",
    'BJ': "R2 S' R2 S R E R2 E' R",
    'BK': "R' S R2 S R' S' R2 S' R2",
    'BL': "R F' R S' R2 S R F R'",
    'BM': "U' R S' R' B' R S R' B U",
    'BN': "U' R' S' R' B' R S R' B R2 U",
    'BO': "S' R' F R S R2 S' R F' R S",
    'BP': "U' S' R' B' R S R' B R U",
    'BR': "R2 S' R2 S R' E' R2 E R'",
    'BS': "R S R2 S R S' R2 S' R2",
    'BT': "R' B R' S' R2 S R' B' R",
    'BW': "R2 S' R2 S",
    'BY': "R' B' R' S' R2 S R' B R",
    'BZ': "R S R2 F' R U R S' R' U' R' F R",
    'CA': "U' R B' R' S R B2 R' S' R B' R' U",
    'CB': "S' R B R S R2 S' R B' R' S",
    'CD': "D' S' R2 S R2 D",
    'CE': "U' M U2 M' U'",
    'CF': "R' B' R U R E' R' U' R E R2 B R",
    'CG': "S R B R2 E R2 E' B' R' S'",
    'CH': "D R F' R S' R2 S R F R' D'",
    'CI': "U' R' B' E' R2 E R2 B R U",
    'CJ': "D' R E R2 E' R D",
    'CK': "R' D' R U D R U' R' D' R' D R2 U R' U'",
    'CL': "U' D S' R' B' R S R' B R U D'",
    'CM': "D' R' S' R' S R2 S' R' S R D",
    'CN': "U' B' E' R2 E R2 B U",
    'CO': "R' B R U' R E R' U R E' R2 B' R",
    'CP': "R' B R S R' B' R S'",
    'CR': "D' R' E' R2 E R' D",
    'CS': "R' U M2 U' R U M2 U'",
    'CW': "R' D R' S' R2 S R' D' R",
    'CY': "R B R' U R E' R' U' R E B' R'",
    'CZ': "U2 R B R' S R B' R' S' U2",
    'DA': "R F R' U R' E R U' R' E' R2 F' R'",
    'DB': "S' R' F' R' S R2 S' R' F R S",
    'DC': "D S' R2 S R2 D'",
    'DE': "U M' U2 M U",
    'DF': "S R' F' R2 E' R2 E F R S'",
    'DG': "U' R' F R U R' E' R U' R' F' R U R' E R",
    'DH': "D' R' B R' S' R2 S R' B' R D",
    'DI': "R' F' R U' R' E R U R' E' F R",
    'DJ': "D R E R2 E' R D'",
    'DK': "R' D R U R U' R2 D' R D R U R' U' D'",
    'DM': "D R' S' R' S R2 S' R' S R D'",
    'DN': "D R S' R S R2 S' R S R' D'",
    'DO': "S R' F R2 E R2 E' F' R S'",
    'DP': "R F' R' S R F R' S'",
    'DR': "R' F' R U' R E' R' U R E R2 F R",
    'DS': "R' U' M2 U R U' M2 U",
    'DT': "U' D' S' R' B' R S R' B R U D",
    'DW': "R' F' R U' R E R' U R E' R2 F R",
    'DY': "U R F' R2 E R2 E' F R' U'",
    'DZ': "U2 R' F' R S R' F R S' U2",
    'EA': "R2 S2 R' U' R S2 R' U R'",
    'EB': "U2 R2 S' R2 U2 S",
    'EC': "U M U2 M' U",
    'ED': "U' M' U2 M U'",
    'EF': "S R E' R2 E R S'",
    'EG': "S R' E R2 E' R' S'",
    'EH': "U2 R S R' U2 R S' R'",
    'EI': "R F R' S R2 S' R' F' R'",
    'EJ': "S R2 S' R' E R2 E' R",
    'EK': "R S' R2 S' R' S R2 S",
    'EL': "R F' R' S R2 S' R' F R'",
    'EM': "U2 R' S' R U2 R' S R",
    'EN': "U2 R S' R' U2 R S R'",
    'EO': "U2 R U R' U R' U' R2 U' R' U R' U R",
    'EP': "R' E' R U2 R' E R U2",
    'ER': "S R2 S' R E' R2 E R'",
    'ES': "U2 R S2 R' U2 R S2 R'",
    'ET': "R' B R S R2 S' R B' R",
    'EW': "S R2 S' R2",
    'EY': "R' B' R S R2 S' R B R",
    'FA': "U R E' R' U' R E R'",
    'FB': "R' E' R S' R E R2 E' R S R' E R",
    'FC': "R' B' R2 E' R' U R E R' U' R' B R",
    'FD': "S R' F' E' R2 E R2 F R S'",
    'FE': "S R' E' R2 E R' S'",
    'FG': "U' R E' R' U R E R2 E R U' R' E' R U",
    'FH': "E' R E R S' R' S R'",
    'FI': "S U' R' E' R2 E R' U S'",
    'FJ': "U' R B R' E' R B' R' U E",
    'FK': "R U R' U' R E' R' U R u' R'",
    'FL': "M' U' R E' R' U R E r'",
    'FM': "U' R2 E' R U R E2 R' U' R u",
    'FN': "u R U' R E R2 E' R U R' u'",
    'FO': "U' R E' R' U R E R'",
    'FP': "U R' F R2 E' R2 E F' R U'",
    'FS': "u R' U' R E R' U R U'",
    'FT': "U D' R' F R2 E' R2 E F' R U' D",
    'FW': "S R' E' R2 E R S' R2",
    'FY': "U R F R2 E' R2 E F' R' U'",
    'FZ': "E' R E R' S R' S' R",
    'GA': "U R' E R U' R' E' R",
    'GB': "R2 S' R' E R2 E' R' S R2",
    'GC': "S R B E R2 E' R2 B' R' S'",
    'GD': "R F R2 E R U' R' E' R U R F' R'",
    'GE': "S R E R2 E' R S'",
    'GF': "R F E' R' U' R E R' U R F' R'",
    'GH': "E R' E' R' S' R S R",
    'GI': "S U' R E R2 E' R U S'",
    'GK': "u' R U R' E' R U' R' U",
    'GL': "R' E R S' R' F' R S R' F E' R",
    'GM': "u' R' U R' E' R2 E R' U' R u",
    'GN': "U' B' R2 E R2 E' B U",
    'GO': "U' R' E R U R' E' R",
    'GP': "U' R B' R2 E R2 E' B R' U",
    'GR': "U R' F' R E R' F R U' E'",
    'GS': "R' U' R U R' E R U' R' u R",
    'GT': "M U R' E R U' R' E' r",
    'GW': "S R E R2 E' R' S' R2",
    'GY': "S U R E R2 E' R U' S'",
    'GZ': "E R' E' R S R S' R'",
    'HA': "U' R S R' U' R S' R' U2",
    'HC': "D R F' R' S' R2 S R' F R' D'",
    'HD': "D' R' B R S' R2 S R B' R D",
    'HE': "R S R' U2 R S' R' U2",
    'HF': "R S' R S R' E' R' E",
    'HG': "R' S' R' S R E R E'",
    'HI': "R' F R' S' R F' R' S R2",
    'HJ': "R' E R S' R2 S R E' R",
    'HK': "E' R' S' R' S R E R",
    'HL': "R' F' R' S' R F R' S R2",
    'HM': "R' u' R U S' R2 S R2 U' R' u R",
    'HN': "R u R' U' S' R2 S R2 U R u' R'",
    'HO': "U R S R' U R S' R' U2",
    'HP': "U' R B' R S' R2 S R B R' U",
    'HR': "R E' R' S' R2 S R' E R'",
    'HS': "E R S' R S R' E' R'",
    'HT': "R B R S' R' B' R S R2",
    'HW': "R E' R' S' R2 S R E R",
    'HY': "R B' R S' R' B R S R2",
    'HZ': "D S R' F' R S' R' F R D'",
    'IA': "U' R B' R' S R B R' S' U",
    'IB': "R F R' S' R2 S R' F' R'",
    'IC': "U' R' B E' R2 E R2 B' R U",
    'ID': "R' F' E R U' R' E' R U R' F R",
    'IE': "R F R S R2 S' R F' R'",
    'IF': "S U' R E' R2 E R U S'",
    'IG': "U' R' B' E R2 E' R2 B R U",
    'IH': "R2 S' R F R' S R F' R",
    'IJ': "R E R' U' R' E' R2 E R' U R E' R'",
    'IK': "S' R S' R' U R S R' U' S",
    'IL': "R F' R2 E R2 E' F R'",
    'IM': "R u' R' E' R2 E R' u R'",
    'IN': "R U R' S' R U R' S R U2 R'",
    'IP': "S' R' F R S R' F' R",
    'IR': "R F R2 E' R2 E F' R'",
    'IS': "S' R' S' R U R' S R U' S",
    'IT': "D' S' R' F R S R' F' R D",
    'IW': "U' R B' R' S' R B R' S U",
    'IY': "U' R' B' R S R2 S' R B R U",
    'IZ': "S R' F R S' R' F' R",
    'JA': "U R E2 R' U' R E2 R'",
    'JB': "R' E R2 E' R' S' R2 S R2",
    'JC': "D' R' E R2 E' R' D",
    'JD': "D R' E R2 E' R' D'",
    'JE': "R' E R2 E' R S R2 S'",
    'JF': "U' E' R B R' E R B' R' U",
    'JH': "R' E R' S' R2 S R' E' R",
    'JI': "R E R' U' R E' R2 E R U R E' R'",
    'JK': "U' R' U R' E R2 E' R' U' R U",
    'JL': "R F' R' U M U' R F R' U M' U'",
    'JM': "S' R' S R' E R2 E' R' S' R S",
    'JN': "R u' R' U R E' R2 E R U' R u R'",
    'JO': "U' R E2 R' U R E2 R'",
    'JP': "S' R' F2 R S R' F2 R",
    'JR': "R' E R2 E' R2 E' R2 E R'",
    'JS': "U' R U R' E R2 E' R' U' R' U",
    'JT': "R' B E R2 E' R2 B' R",
    'JW': "R' E R2 E' R'",
    'JY': "R' B' E R2 E' R2 B R",
    'JZ': "S R' F2 R S' R' F2 R",
    'KA': "u R' E R U' R' E' R E",
    'KB': "R2 S R2 S R S' R2 S' R",
    'KC': "U R U' R2 D' R D R U R' U' D' R' D R",
    'KD': "U D R U' R' D' R' D R2 U R' U' R' D' R",
    'KE': "S' R2 S' R S R2 S R'",
    'KF': "R u R' U' R E R' U R U' R'",
    'KG': "u R' F' R E R' F R U'",
    'KH': "R' E' R' S' R S R E",
    'KI': "S' U R S' R' U' R S R' S",
    'KJ': "U' R' U R E R2 E' R U' R U",
    'KL': "U M' U' R U M U' R'",
    'KM': "U R U' R' E' R U R' u'",
    'KO': "U' E' R' E R U R' E' R E",
    'KP': "R u' R' U R E' R' U' R U R'",
    'KR': "U' R' U R' E' R2 E R' U' R U",
    'KS': "U2 R' S R2 S' R' U2",
    'KT': "U' M U R U' M' U R'",
    'KW': "U R U' R' D' R' D R2 U R' U' R' D' R D",
    'KY': "S' U' R S' R' U R S R' S",
    'KZ': "U' M' U R U' M U R'",
    'LA': "U D R' E' R U' R' E R D'",
    'LB': "R F' R' S' R2 S R' F R'",
    'LC': "U' D R' B' R S' R' B R S U D'",
    'LE': "R F' R S R2 S' R F R'",
    'LF': "U' R' F' R U R E' R' U' R E R2 F R U",
    'LG': "R' E F' R S' R' F R S R' E' R",
    'LH': "R2 S' R F' R' S R F R",
    'LI': "R F R2 E R2 E' F' R'",
    'LJ': "U M U' R F' R' U M' U' R F R'",
    'LK': "R U M' U' R' U M U'",
    'LM': "E' R U M' U' R' U M u'",
    'LN': "R' F2 R E' R' F' R E R' F' R",
    'LO': "r U' R' U M U' R U R'",
    'LP': "S' R' F' R S R' F R",
    'LR': "R F' R2 E' R2 E F R'",
    'LS': "R' U M' U' R U M U'",
    'LT': "U' D' R B' R S' R2 S R B R' U D",
    'LW': "U M U' R F R' U M' U' R F' R'",
    'LY': "D R B' R' S' R B R' S D'",
    'LZ': "S R' F' R S' R' F R",
    'MA': "U' R' S' R U' R' S R U2",
    'MB': "S R2 S' R2 S' R S R2 S R S'",
    'MC': "D' R S R S' R2 S R S' R' D",
    'MD': "D R S R S' R2 S R S' R' D'",
    'ME': "R' S' R U2 R' S R U2",
    'MF': "U F E' R2 E R2 F' U'",
    'MG': "u' R' U R E' R2 E R U' R u",
    'MH': "R' u' R U R2 S' R2 S U' R' u R",
    'MI': "R u' R E' R2 E R u R'",
    'MJ': "S' R' S R E R2 E' R S' R S",
    'MK': "u R U' R' E R U R' U'",
    'ML': "S' R' U M' U2 M U R S",
    'MN': "S' R S R2 S' R S",
    'MO': "U R' S' R U R' S R U2",
    'MP': "U' R U S U' R' U S'",
    'MR': "R' u R U' R E R2 E' R U R' u' R",
    'MT': "R B' R' E R B' R' E' R B2 R'",
    'MW': "R S R S' R2 S R S' R'",
    'MY': "R' U2 R S' R' U R S R' U R",
    'MZ': "R' U2 R S' R' U2 R S",
    'NA': "U' R S' R' U' R S R' U2",
    'NB': "U' R2 B' R S' R' B R S R U",
    'NC': "U' B E' R2 E R2 B' U",
    'ND': "D R S' R' S R2 S' R' S R' D'",
    'NE': "R S' R' U2 R S R' U2",
    'NF': "R S' R' S R E' R2 E R S' R S R'",
    'NG': "U' B' E R2 E' R2 B U",
    'NH': "R u R' U' R2 S' R2 S U R u' R'",
    'NI': "R U2 R' S' R U' R' S R U' R'",
    'NJ': "R u' R' U R' E' R2 E R' U' R u R'",
    'NL': "R U F' R2 E R2 E' F U' R'",
    'NM': "S' R' S R2 S' R' S",
    'NO': "U R S' R' U R S R' U2",
    'NP': "U' R' U S U' R U S'",
    'NR': "u' R' U R' E R U' R' E' R2 u",
    'NS': "u' R' U R E' R' U' R U",
    'NT': "u' M U R' U' M' U R E'",
    'NW': "R S' R' S R2 S' R' S R'",
    'NY': "R U2 R' S' R U R' S R U R'",
    'NZ': "R U2 R' S' R U2 R' S",
    'OA': "R' U' R U R U2 R' U' R' U R2 U2 R'",
    'OB': "S' R' F R' S R2 S' R' F' R S",
    'OC': "R' B R2 E R' U' R E' R' U R' B' R",
    'OD': "S R' F E R2 E' R2 F' R S'",
    'OE': "R U R S2 R' U' R S2 R2",
    'OF': "R E' R' U' R E R' U",
    'OG': "R' E R U' R' E' R U",
    'OH': "U2 R S R' U' R S' R' U'",
    'OJ': "R E2 R' U' R E2 R' U",
    'OK': "E' R' E R U' R' E' R U E",
    'OL': "R U' R' U M' U' R U r'",
    'OM': "U2 R' S' R U' R' S R U'",
    'ON': "U2 R S' R' U' R S R' U'",
    'OP': "R' E' R U' R' E R U",
    'OR': "R' E2 R U' R' E2 R U",
    'OS': "E R E' R' U' R E R' u",
    'OT': "D' R' E' R U' R' E R U D",
    'OW': "R E' R2 E R U' R' E' R2 E R' U",
    'OY': "U S R' F R S' R' F' R U'",
    'OZ': "S U' R' E' R U R' E R S'",
    'PA': "U R' E' R U' R' E R",
    'PB': "U' R' B' R S' R' B R S U",
    'PC': "S R' B R S' R' B' R",
    'PD': "S R F' R' S' R F R'",
    'PE': "U2 R' E' R U2 R' E R",
    'PF': "U R' F E' R2 E R2 F' R U'",
    'PG': "U' R B' E R2 E' R2 B R' U",
    'PH': "U R' F R S' R2 S R F' R U'",
    'PI': "R' F R S' R' F' R S",
    'PJ': "R' F2 R S' R' F2 R S",
    'PK': "R U' R' U R E R' U' R u R'",
    'PL': "R' F' R S' R' F R S",
    'PM': "S U' R U S' U' R' U",
    'PN': "S U' R' U S' U' R U",
    'PO': "U' R' E' R U R' E R",
    'PR': "R B2 R' S' R B2 R' S",
    'PS': "R' U R U' R' E' R U R' u' R",
    'PT': "R B R' S' R B' R' S",
    'PY': "R B' R' S' R B R' S",
    'PZ': "D' S R' F' R S' R' F R D",
    'RA': "U R' E2 R U' R' E2 R",
    'RB': "R E' R2 E R S' R2 S R2",
    'RC': "D' R E' R2 E R D",
    'RD': "D R E' R2 E R D'",
    'RE': "R E' R2 E R' S R2 S'",
    'RG': "U' R' E2 R U R' E' R U' R' E' R U",
    'RH': "R E' R S' R2 S R E R'",
    'RI': "R F E' R2 E R2 F' R'",
    'RJ': "R E' R2 E R2 E R2 E' R",
    'RK': "U' R' U R E' R2 E R U' R U",
    'RL': "R F' E' R2 E R2 F R'",
    'RM': "R' u R U' R' E R2 E' R' U R' u' R",
    'RN': "R U F E' R2 E R2 F' U' R'",
    'RO': "U' R' E2 R U R' E2 R",
    'RP': "S' R B2 R' S R B2 R'",
    'RS': "U' R U R E' R2 E R U' R' U",
    'RT': "R' B R U' M' U R' B' R U' M U",
    'RW': "R E' R2 E R",
    'RY': "R' E' R U R' E R2 E' R' U' R' E R",
    'RZ': "S R B2 R' S' R B2 R'",
    'SA': "U E R E' R' U' R E R' E'",
    'SB': "R2 S R2 S R' S' R2 S' R'",
    'SC': "U M2 U' R' U M2 U' R",
    'SD': "U' M2 U R' U' M2 U R",
    'SE': "S' R2 S' R' S R2 S R",
    'SF': "S' R E' R' E R' S R",
    'SG': "R' u' R U R' E' R U' R' U R",
    'SH': "R E R S' R' S R' E'",
    'SI': "S' U R' S' R U' R' S R S",
    'SJ': "U' R U R E R2 E' R U' R' U",
    'SK': "U2 R S R2 S' R U2",
    'SL': "U M' U' R' U M U' R",
    'SN': "U' R' U R E R' U' R u",
    'SO': "u' R E' R' U R E R' E'",
    'SP': "S' R' U' R U S U' R' U R",
    'SR': "U' R U R' E' R2 E R' U' R' U",
    'ST': "U' M U R' U' M' U R",
    'SW': "U' R' U R D R D' R2 U' R U R D R' D'",
    'SY': "S' U' R' S' R U R' S R S",
    'SZ': "U' M' U R' U' M U R",
    'TA': "r' U R U' M' U R' U' R",
    'TB': "R' B R S' R2 S R B' R",
    'TD': "U' D' R' B' R S' R' B R S U D",
    'TE': "R' B R' S R2 S' R' B' R",
    'TF': "U D' R' F E' R2 E R2 F' R U' D",
    'TG': "r' E R U R' E' R U' M'",
    'TH': "R2 S' R' B R S R' B' R'",
    'TI': "D' R' F R S' R' F' R S D",
    'TJ': "R' B R2 E R2 E' B' R",
    'TK': "R U' M U R' U' M' U",
    'TL': "U' D R B' R S' R2 S R B R' U D'",
    'TM': "M U2 R' S' R U R' S R U M'",
    'TN': "M U2 R S' R' U R S R' U M'",
    'TO': "U M U M' U M U M'",
    'TP': "S' R B R' S R B' R'",
    'TR': "U' M' U R' B R U' M U R' B' R",
    'TS': "R' U' M U R U' M' U",
    'TW': "U' M' U R' B' R U' M U R' B R",
    'TY': "R' B E' R2 E R2 B' R",
    'TZ': "S R B R' S' R B' R'",
    'WA': "U R E' R2 E R U' R' E' R2 E R'",
    'WB': "S' R2 S R2",
    'WC': "R' D R S' R2 S R D' R",
    'WD': "R' D' R S' R2 S R D R",
    'WE': "R2 S R2 S'",
    'WF': "S' R E' R2 E R' S R2",
    'WG': "S' R' E R2 E' R S R2",
    'WH': "R E R S' R2 S R' E' R",
    'WI': "U' S' R B' R' S R B R' U",
    'WJ': "R E R2 E' R",
    'WK': "D' R' D R U R U' R2 D' R D R U R' U'",
    'WL': "R F R' U M U' R F' R' U M' U'",
    'WM': "R' S' R' S R2 S' R' S R",
    'WN': "R S' R S R2 S' R S R'",
    'WO': "U' R E' R2 E R U R' E' R2 E R'",
    'WR': "R' E' R2 E R'",
    'WS': "D R D' R' U' R' U R2 D R' D' R' U' R U",
    'WT': "R' B' R U' M' U R' B R U' M U",
    'WY': "U S' R' F R S R' F' R U'",
    'WZ': "R' E' R S R2 S' R' E R'",
    'YB': "R' B' R S' R2 S R B R",
    'YC': "R B E' R' U R E R' U' R B' R'",
    'YD': "U R F R2 E R2 E' F' R' U'",
    'YE': "R' B' R' S R2 S' R' B R",
    'YF': "U R F E' R2 E R2 F' R' U'",
    'YG': "S U R' E R2 E' R' U' S'",
    'YH': "R2 S' R' B' R S R' B R'",
    'YI': "U' R' B' R' S R2 S' R' B R U",
    'YJ': "R' B' R2 E R2 E' B R",
    'YK': "S' R S' R' U' R S R' U S",
    'YL': "D S' R B' R' S R B R' D'",
    'YM': "S' R S2 R' U' R S2 R' U S",
    'YN': "R' u R E R2 E' R u' R",
    'YO': "U R' F R S R' F' R S' U'",
    'YP': "S' R B' R' S R B R'",
    'YR': "R' E' R U R E R2 E' R U' R' E R",
    'YS': "S' R' S' R U' R' S R U S",
    'YT': "R' B' E' R2 E R2 B R",
    'YW': "U R' F R S' R' F' R S U'",
    'YZ': "S R B' R' S' R B R'",
    'ZA': "S R' E' R U R' E R U' S'",
    'ZB': "R' F' R U R S R' U' R S' R2 F R",
    'ZC': "U2 S R B R' S' R B' R' U2",
    'ZD': "U2 S R' F' R S' R' F R U2",
    'ZF': "R' S R S' R E' R' E",
    'ZG': "R S R' S' R' E R E'",
    'ZH': "R' S R S' R2 S' R' S R'",
    'ZI': "R' F R S R' F' R S'",
    'ZJ': "R' F2 R S R' F2 R S'",
    'ZK': "R U M U' R' U M' U'",
    'ZL': "R' F' R S R' F R S'",
    'ZM': "S' R' U2 R S R' U2 R",
    'ZN': "S' R U2 R' S R U2 R'",
    'ZO': "S R' E' R U' R' E R U S'",
    'ZP': "D' R' F' R S R' F R S' D",
    'ZR': "R B2 R' S R B2 R' S'",
    'ZS': "R' U M U' R U M' U'",
    'ZT': "R B R' S R B' R' S'",
    'ZW': "R E' R S R2 S' R' E R",
    'ZY': "R B' R' S R B R' S'",
}
